name: hacker_news
description: The Boring Flutter Developement Tutorial Learnings.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.25.0
  built_collection: ^4.3.2
  built_value: ^7.1.0
  url_launcher : ^5.7.10
  font_awesome_flutter : ^8.12.0
  http: ^0.12.2
  webview_flutter: ^1.0.7
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true